### ISSUE TITLE
SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by ABThijssen** [abraham-abin13/gsel_vec#1]
Hi,

Thanks for developing this interesting package! I have used it a couple of months ago to run some initial analyses, but now that I want to use it again I can't seem to get it to work anymore. I keep getting the following error and have tried to use newer versions of anaconda and python, but that didn't solve the problem. How should I solve this issue?

Traceback (most recent call last):
  File "/home/anais1/.conda/envs/evo_dask/bin/top_gsel_vec.py", line 9, in <module>
    from gsel_vec import run_evo_sig
  File "/home/anais1/.conda/envs/evo_dask/lib/python3.6/site-packages/gsel_vec/run_evo_sig.py", line 20,                                      in <module>
    import numpy as np
  File "/sw/arch/RHEL8/EB_production/2022/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-p                                     ackages/numpy/__init__.py", line 144, in <module>
    from . import core
  File "/sw/arch/RHEL8/EB_production/2022/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-p                                     ackages/numpy/core/__init__.py", line 9, in <module>
    from numpy.version import version as __version__
  File "/sw/arch/RHEL8/EB_production/2022/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-p                                     ackages/numpy/version.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

**Comment by ABThijssen** [comment]
I solved the issue. Python 3.10 is loaded automatically when I access the cluster computer, which gave the error.
Entering "module purge" before using the package was all it took to solve this
